### ISSUE TITLE
Does this work on KDE?

### ISSUE THREAD

**Issue by virtualritz** [amrbashir/system_tray#20] opened 2023-02-07 13:41 UTC
When I run a test app on KDE (Kubuntu) I don't get any tray icon but my log gets:

```
(process:56879): Gtk-CRITICAL **: 14:39:36.342: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:56879): GLib-GObject-WARNING **: 14:39:36.342: invalid (NULL) pointer instance

(process:56879): GLib-GObject-CRITICAL **: 14:39:36.342: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by FabianLars** [comment] 2023-02-07 14:27
Possible duplicate of <https://github.com/tauri-apps/tray-icon/issues/13>? (can you check if that applies to you?)

**Comment by virtualritz** [comment] 2023-02-07 23:53
This is an `egui` (`eframe`) app.
If I add:

```rust
gtk::init().unwrap();
```

the errors disappears and I instead get:

```
Gtk-Message: 00:49:14.151: Failed to load module ""appmenu-gtk-module""
```

but still no tray icon.

I tried:
```
sudo apt reinstall appmenu-gtk3-module appmenu-gtk2-module
```

but no cigar.

**Comment by FabianLars** [comment] 2023-02-08 07:56
but you do have libappindicator (can't remember the exact package name) or libayatana-appindicator3-dev installed, right?

**Comment by virtualritz** [comment] 2023-02-08 12:16
> but you do have libappindicator (can't remember the exact package name) or libayatana-appindicator3-dev installed, right?

Yes, both.

**Comment by amrbashir** [comment] 2023-02-08 18:02
Unfortunately on Linux, sometimes you need to set a menu (an empty one will do) I will update the docs accordingly.

here is an example with egui:
```rs
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")] // hide console window on Windows in release

use eframe::egui;

fn main() -> Result<(), eframe::Error> {
    // Log to stdout (if you run with `RUST_LOG=debug`).
    tracing_subscriber::fmt::init();

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/examples/icon.png");
    let icon = load_icon(std::path::Path::new(path));

    #[cfg(target_os = "linux")]
    std::thread::spawn(|| {
        use tray_icon::{menu::Menu, TrayIconBuilder};

        gtk::init().unwrap();
        let tray_icon = TrayIconBuilder::new()
            .with_menu(Box::new(Menu::new()))
            .with_icon(icon)
            .build()
            .unwrap();

        gtk::main();
    });

    #[cfg(not(target_os = "linux"))]
    let tray_icon = TrayIconBuilder::new().with_icon(icon).build().unwrap();

    let options = eframe::NativeOptions {
        initial_window_size: Some(egui::vec2(320.0, 240.0)),
        ..Default::default()
    };

    eframe::run_native(
        "My egui App",
        options,
        Box::new(|_cc| Box::new(MyApp::default())),
    )
}

struct MyApp {
    name: String,
    age: u32,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            name: "Arthur".to_owned(),
            age: 42,
        }
    }
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        use tray_icon::{menu::MenuEvent, TrayEvent};

        if let Ok(event) = TrayEvent::receiver().try_recv() {
            println!("tray event: {:?}", event);
        }

        if let Ok(event) = MenuEvent::receiver().try_recv() {
            println!("menu event: {:?}", event);
        }

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("My egui Application");
            ui.horizontal(|ui| {
                let name_label = ui.label("Your name: ");
                ui.text_edit_singleline(&mut self.name)
                    .labelled_by(name_label.id);
            });
            ui.add(egui::Slider::new(&mut self.age, 0..=120).text("age"));
            if ui.button("Click each year").clicked() {
                self.age += 1;
            }
            ui.label(format!("Hello '{}', age {}", self.name, self.age));
        });
    }
}

fn load_icon(path: &std::path::Path) -> tray_icon::icon::Icon {
    let (icon_rgba, icon_width, icon_height) = {
        let image = image::open(path)
            .expect("Failed to open icon path")
            .into_rgba8();
        let (width, height) = image.dimensions();
        let rgba = image.into_raw();
        (rgba, width, height)
    };
    tray_icon::icon::Icon::from_rgba(icon_rgba, icon_width, icon_height)
        .expect("Failed to open icon")
}

```

but keep in mind that on Linux you need to modify the icon from within the thread that created it. It is a bit annoying but unfortunately.

**Closed as completed by amrbashir** 2023-02-08 18:02 UTC

**Comment by virtualritz** [comment] 2023-02-10 14:20
Yes, this works for me. Thanks heaps!
