### ISSUE TITLE
tray icon menu renders under taskbar

### ISSUE THREAD

**Issue by redtomato34** [amrbashir/system_tray#143] opened 2024-04-25 08:50 UTC
Opening and closing windows 11 tray quick settings then opening menu on own tray app renders the menu under the taskbar. Not able to close it unless right clicking on it then left clicking off it.
![image](https://github.com/tauri-apps/tray-icon/assets/168075664/ada04b79-74aa-4a31-b2b1-d4fd99ad316a)

**Comment by redtomato34** [comment] 2024-04-25 08:53
Works fine if in hidden icon menu.

**Comment by amrbashir** [comment] 2024-04-29 16:17
I can't seem to reproduce, can you explain in more detail how to reproduce?

**Comment by redtomato34** [comment] 2024-04-29 19:53
After some testing, this seems to be an issue with Windows instead of anything app/crate related. However, here are the steps to reproduce: 

1. Using the tao example, cargo run to start the application
2. App icon should display inside the hidden tray icon menu (if enabled)
3. Right clicking on the app icon should display the menu normally
4. Navigate to system taskbar settings. Settings > Personalization > Taskbar
5. Open "Other system tray icons" and toggle on personal application to show outside the hidden tray icon menu
6. App icon should display outside the hidden tray icon menu
7. Right clicking on the app icon should display the menu normally
8. Open the windows tray quick settings by left clicking on either the wifi or volume icon
9. Close the quick settings by left clicking on the icons again or outside the menu
10. Right clicking on app icon should display the menu under the taskbar (unintended behavior)

Notes:
Right clicking anywhere besides any app's tray icon after closing the system quick settings menu then opening app menu does not cause unintended behavior.
Same steps can be taken with winit example.
Other apps with a tray menu have the same unintended behavior.

**Comment by amrbashir** [comment] 2024-04-29 21:04
alright, thank you for investigating further, since this is something the OS should handle, gonna close this issue

**Closed as not planned by amrbashir** 2024-04-29 21:04 UTC

**Comment by Legend-Master** [comment] 2024-04-30 07:20
Just want to add in an easier reproduce steps for future readers

1. right click a tray icon (e.g. WLAN)
2. hover the mouse on a task bar window icon (e.g. Chrome)
