### ISSUE TITLE
"assertion 'GTK_IS_WINDOW (window)' failed" when clicking on the egui example on Linux

### ISSUE THREAD

**Issue by 4JX** [amrbashir/system_tray#85] opened 2023-09-25 17:15 UTC
I'm getting the following error whenever I click on the tray icon if it includes a `with_menu` builder section.
```
(legion-kb-rgb:1553719): Gtk-CRITICAL **: 19:05:37.050: gtk_window_set_accept_focus: assertion 'GTK_IS_WINDOW (window)' failed
zsh: segmentation fault (core dumped)  nix run . -L --
```

Current test code is [here](https://github.com/4JX/L5P-Keyboard-RGB/blob/e01a712e8752c54dc41ef2bb99244466d67ba273/app/src/main.rs#L94-L144) which is a slightly changed version of [the egui example](https://github.com/tauri-apps/tray-icon/blob/dev/examples/egui.rs), which exhibits the same behavior.

Using GNOME 44.3 with the extension "Tray Icons: Reloaded" to be able to display them. (May has something to do with it? Every other app works fine though.)

**Comment by amrbashir** [comment] 2023-10-25 22:28
Hi, sorry for the very late response, Can you try with the `egui` example in this repo without any modificatios or better with the `tao` example?

**Comment by 4JX** [comment] 2023-10-26 17:05
Trying to run either of the examples under GNOME with [Tray Icons: Reloaded](https://github.com/MartinPL/Tray-Icons-Reloaded) results in the error above, using [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) or testing in a Plasma session gives `(legion-kb-rgb:536076): LIBDBUSMENU-GLIB-WARNING **: 19:02:55.231: About to Show called on an item wihtout submenus.  We're ignoring it.` instead.

**Comment by amrbashir** [comment] 2023-10-27 02:53
This error seems like https://github.com/tauri-apps/tray-icon/issues/89 so I will go ahead and close this since I can't reproduce your initial issue.

**Closed as not planned by amrbashir** 2023-10-27 02:53 UTC
